const Map<String, String> ar = {
  'login': 'تسجيل الدخول',
  'signup': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'welcome to east news': 'مرحبًا بكم في إيست نيوز',
  "Don'tHaveAnAccount": "ليس لديك حساب",
  "let's create account": "لنقم بإنشاء حساب",
  "userName": "اسم المستخدم",
  'confirm password': "تأكيد كلمة المرور",
  'all': "الكل",
  'sport': 'الرياضة',
  'entertainment': 'الترفيه',
  'business': 'الأعمال',
  'science': 'العلوم',
  'health': 'الصحة',
  'home': "الرئيسية",
  'save': "حفظ",
  'settings': 'الإعدادات',
  'logout': "تسجيل الخروج",
  'delete': 'حذف',
  'summary': "الملخص",
  'technology': 'التكنولوجيا',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  'language': 'اللغة',
  'logoutMessage': "تحتاج إلى تسجيل الخروج",
  'close': 'إغلاق',
  'unSave': 'إلغاء الحفظ',
  'E': 'إي',
  'ASTNEWS': 'نيوز',
  'HaveAnAccount?': 'هل لديك حساب؟'
};
