const Map<String, String> ar = {
  'login': 'تسجيل الدخول',
  'signup': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'welcome to east news': 'مرحبًا بكم في إيست نيوز',
  "Don'tHaveAnAccount": "ليس لديك حساب ",
  "let's create account": "لنقم بإنشاء حساب",
  "userName": "اسم المستخدم",
  'confirm password': "تأكيد كلمة المرور",
  'all': "الكل",
  'sports': 'الرياضة',
  'entertainment': 'الترفيه',
  'textReader': 'الاستماع الي الخبر',
  'business': 'الأعمال',
  'science': 'العلوم',
  'health': 'الصحة',
  'home': "الرئيسية",
  'save': "حفظ",
  'settings': 'الإعدادات',
  'logout': "تسجيل الخروج",
  'delete': 'حذف',
  'summary': "الملخص",
  'technology': 'التكنولوجيا',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  'language': 'اللغة',
  'logoutMessage': "تحتاج إلى تسجيل الخروج",
  'close': 'إغلاق',
  'unSave': 'إلغاء الحفظ',
  'E': 'إي',
  'ASTNEWS': 'نيوز',
  'HaveAnAccount?': 'هل لديك حساب؟',
  'Comments': 'التعليقات',
  'Add a comment': 'اضف تعليق',
  'Summarize' : 'تلخيص',
  'Skip' : 'تخطي',
  'next': 'التالي',
  'Please wait' :'من فضلك انتظر',
  'SHARE WITH US YOUR INTEREST' : 'شاركنا اهتمامتك',
  'Edit comment' : 'تعديل التعليق',
  'Comment Edit' : 'تم التعديل',
  'Password is Required'  : 'كلمة السر مطلوبة'
};
