const Map<String, String> en = {
  'login': 'Login',
  'signup': 'Signup',
  'email': 'Email',
  'password': 'Password',
  'textReader': 'Listen to article',
  'welcome to east news': 'WELCOME TO EAST NEWS',
  "Don'tHaveAnAccount": "Don't have an account",
  "let's create account": "LET's CREATE ACCOUNT",
  "userName": "User Name",
  'confirm password': "Confirm password",
  'all': "All",
  'sports': 'Sports',
  'entertainment': 'Entertainment',
  'business': 'Business',
  'science': 'Science',
  'health': 'health',
  'home': "Home",
  'save': "Save",
  'settings': 'Settings',
  'logout': "Logout",
  'delete': 'Delete',
  'Edit':'Edit',
  'summary': "Summary",
  'technology': 'Technology',
  'english': 'English',
  'arabic': 'Arabic',
  'language': 'Language',
  'logoutMessage': "You need to logout",
  'close': 'close',
  'unSave': 'un save',
  'E': 'E',
  'ASTNEWS': 'AST NEWS',
  'HaveAnAccount?': 'Have an account?',
  'Comments': 'Comments',
  'Add a comment': 'Add a comment',
  'Summarize': 'Summarize',
  'Skip': 'Skip',
  'next': 'next',
  'Please wait': 'Please wait …',
  'SHARE WITH US YOUR INTEREST': 'SHARE WITH US YOUR INTEREST',
  'Edit comment': 'Edit comment',
  'Comment Edit' : 'Comment Edit',
  'Password is Required' : 'Password is Required'
};
